/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HafizaOyunu;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.Timer;

/**
 *
 * @author Aedamantium
 */
public class HafizaOyunu extends javax.swing.JFrame {
   
    int kapali1 = 0;
    public int counter = 0;
    int to = 0;
    public int time = 1000;
    public Random generator = new Random();
    int tiklanmaKontrolu = 0;
    
    public ArrayList<JButton> list1 = new ArrayList<>();
    public ArrayList<ImageIcon> list2 = new ArrayList<>();
    public ArrayList<ImageIcon> list3 = new ArrayList<>();
   
    
            int x = 0; //random cozme butonu icin degisken
            int y = 0; //random cozme butonu icin degisken
    
    
    
    /**
     * Creates new form Odev_2
     */
    public HafizaOyunu() {
        initComponents();
        
        jLabel8.setVisible(false);
        list3.clear();
        int[] dizi = new int[20];
         
         ImageIcon karpuz,ananas,cilek,
                   domates,havuc,
                   kiraz,kivi,muz,
                   patlican,portakal;
         
         karpuz = new ImageIcon("icon/karpuz.png");      
         ananas = new ImageIcon("icon/ananas.png");      
         cilek = new ImageIcon("icon/cilek.png");        
         domates = new ImageIcon("icon/domates.png");    
         havuc = new ImageIcon("icon/havuc.png");        
         kiraz = new ImageIcon("icon/kiraz.png");        
         kivi = new ImageIcon("icon/kivi.png");          
         muz = new ImageIcon("icon/muz.png");            
         patlican = new ImageIcon("icon/patlican.png");
         portakal = new ImageIcon("icon/portakal.png");  
         
         list2.add(karpuz);    
         list2.add(ananas);    
         list2.add(cilek);     
         list2.add(domates);   
         list2.add(havuc);    
         list2.add(kiraz);     
         list2.add(kivi);      
         list2.add(muz);       
         list2.add(patlican);  
         list2.add(portakal);  
         list2.add(karpuz);    
         list2.add(ananas);    
         list2.add(cilek);     
         list2.add(domates);   
         list2.add(havuc);    
         list2.add(kiraz);     
         list2.add(kivi);      
         list2.add(muz);       
         list2.add(patlican);  
         list2.add(portakal);  
         
        list1.add(b1);  
        list1.add(b2);
        list1.add(b3);
        list1.add(b4);
        list1.add(b5);
        list1.add(b6);
        list1.add(b7);
        list1.add(b8);
        list1.add(b9);
        list1.add(b10);  
        list1.add(b11);
        list1.add(b12);
        list1.add(b13);
        list1.add(b14);
        list1.add(b15);
        list1.add(b16);
        list1.add(b17);
        list1.add(b18);
        list1.add(b19);
        list1.add(b20);
        
         int a;         
         int sayac = 0;
        
        
        a = generator.nextInt(20)+1;
        dizi[0] = a;
        for (int k = 1; k < dizi.length;) {
            sayac = 0;
            a = generator.nextInt(20)+1;
            //System.out.println(a+" ");
            for (int j = 0; j < dizi.length; j++) {
                if (dizi[j] == a) {
                    sayac++;  break;                  
                }
            }
            if (sayac == 0) {
                dizi[k] = a; k++;  
                
            }
            else continue;
        }
        
        for (int k = 0; k < list2.size() ; k++) {
            list3.add(list2.get(dizi[k]-1));            
            //list1.get(k).setIcon(list2.get(dizi[k]-1));
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        b10 = new javax.swing.JButton();
        b11 = new javax.swing.JButton();
        b12 = new javax.swing.JButton();
        b13 = new javax.swing.JButton();
        b14 = new javax.swing.JButton();
        b15 = new javax.swing.JButton();
        b16 = new javax.swing.JButton();
        b17 = new javax.swing.JButton();
        b18 = new javax.swing.JButton();
        b19 = new javax.swing.JButton();
        b20 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tekrarOyna = new javax.swing.JButton();
        ipucu = new javax.swing.JButton();
        coz = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        b1.setPreferredSize(new java.awt.Dimension(75, 75));
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b(evt);
            }
        });

        b2.setPreferredSize(new java.awt.Dimension(75, 75));
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b(evt);
            }
        });

        b3.setPreferredSize(new java.awt.Dimension(75, 75));
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b(evt);
            }
        });

        b4.setPreferredSize(new java.awt.Dimension(75, 75));
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b(evt);
            }
        });

        b5.setPreferredSize(new java.awt.Dimension(75, 75));
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b(evt);
            }
        });

        b6.setPreferredSize(new java.awt.Dimension(75, 75));
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b(evt);
            }
        });

        b7.setPreferredSize(new java.awt.Dimension(75, 75));
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b(evt);
            }
        });

        b8.setPreferredSize(new java.awt.Dimension(75, 75));
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b(evt);
            }
        });

        b9.setPreferredSize(new java.awt.Dimension(75, 75));
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b(evt);
            }
        });

        b10.setPreferredSize(new java.awt.Dimension(75, 75));
        b10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b(evt);
            }
        });

        b11.setPreferredSize(new java.awt.Dimension(75, 75));
        b11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b(evt);
            }
        });

        b12.setPreferredSize(new java.awt.Dimension(75, 75));
        b12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b(evt);
            }
        });

        b13.setPreferredSize(new java.awt.Dimension(75, 75));
        b13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b(evt);
            }
        });

        b14.setPreferredSize(new java.awt.Dimension(75, 75));
        b14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b(evt);
            }
        });

        b15.setPreferredSize(new java.awt.Dimension(75, 75));
        b15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b(evt);
            }
        });

        b16.setPreferredSize(new java.awt.Dimension(75, 75));
        b16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b(evt);
            }
        });

        b17.setPreferredSize(new java.awt.Dimension(75, 75));
        b17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b(evt);
            }
        });

        b18.setPreferredSize(new java.awt.Dimension(75, 75));
        b18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b(evt);
            }
        });

        b19.setPreferredSize(new java.awt.Dimension(75, 75));
        b19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b(evt);
            }
        });

        b20.setPreferredSize(new java.awt.Dimension(75, 75));
        b20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b(evt);
            }
        });

        jLabel1.setText("TAHMIN SAYISI: ");

        jLabel2.setText("0");

        jLabel3.setText("EN İYİ TAHMİN SAYISI:");

        jLabel4.setText("0");

        tekrarOyna.setText("TEKRAR OYNA");
        tekrarOyna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b(evt);
            }
        });

        ipucu.setText("KARTLARI GÖSTER(İPUCU)");
        ipucu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b(evt);
            }
        });

        coz.setText("ÇÖZ");
        coz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b(evt);
            }
        });

        jComboBox1.setMaximumRowCount(4);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1sn", "1.5sn", "2sn", "2.5sn" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        jLabel6.setText("Bekleme Süresi");

        jLabel8.setText("OYUN BİTTİ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(b16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(b11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(b6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(b1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(11, 11, 11)))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(b17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(b13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(b14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(b18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(b19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(ipucu, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addContainerGap(164, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(coz, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tekrarOyna, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(32, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(b1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(b2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(b4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(b5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tekrarOyna)
                        .addGap(7, 7, 7)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(coz))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(b15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(b13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(b16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(b17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(b19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addComponent(ipucu)))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    int kontrol2 = 0;
    int kontrol = 0; 
    int kapali = 0;
    int counter1 = 0;
    JButton a = null;
    JButton b = null;
    private void b(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b
        // TODO add your handling code here:
        counter1++;
        JButton b = (JButton) evt.getSource();
        
        //Ana Butonlar
        if (kontrol2 == 0 && tiklanmaKontrolu == 0) {
             
        if(b != tekrarOyna && b != coz && b != ipucu){            
        if (counter % 2 == 0) {
             b.setIcon(list3.get(list1.indexOf(b)));
             a = b;
        }
        
        else{
            b.setIcon(list3.get(list1.indexOf(b)));
            if (a.getIcon() == b.getIcon() && a != b) {
                kontrol2++;
                kapali++;
                Timer t = new Timer(time, new ActionListener() { 
                    
                 @Override
                 public void actionPerformed(ActionEvent e) {
                    a.setIcon(null);
                    a.setEnabled(false); 
                    b.setIcon(null);
                    b.setEnabled(false);
                    kontrol2 = 0;      
                    
                    jLabel2.setText((counter1/2)+"");
                    if (kapali == 10) {
                        jLabel8.setVisible(true);
                        coz.setEnabled(false);
                        ipucu.setEnabled(false);
                        if (Integer.parseInt(jLabel4.getText()) == 0 ) {
                            jLabel4.setText(jLabel2.getText());
                        }
                        else if (Integer.parseInt(jLabel2.getText()) < Integer.parseInt(jLabel4.getText())) {
                            jLabel4.setText(jLabel2.getText());
                        }
                        else {
                            jLabel4.setText(jLabel4.getText());
                        }
                    }
                    
                 }});  
    
              t.setRepeats(false);        
              t.start();
              
               
            }   
            
            else if(a.getIcon() != b.getIcon()) {
                kontrol2++;
                Timer t = new Timer(time, new ActionListener() {         
                 @Override
                 public void actionPerformed(ActionEvent e) { 
                   
                   a.setIcon(null);
                   b.setIcon(null);
                   jLabel2.setText((counter1/2)+"");
                   kontrol2 = 0;
                 }});  
    
                 t.setRepeats(false);        
                 t.start();
                 
            }
        }
       
        counter++;
        }
        }
           
        
        //Meyveleri karistirarak oyunu bastan alma butonu
        if (b == tekrarOyna) {
            
            kapali = 0;
            
            if (kapali1 == 10 || to != 0) {
                this.dispose();
                java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                new HafizaOyunu().setVisible(true);
               
                }
                });
            }
            
        jLabel8.setVisible(false);
        list1.clear();
        list1.add(b1);  
        list1.add(b2);
        list1.add(b3);
        list1.add(b4);
        list1.add(b5);
        list1.add(b6);
        list1.add(b7);
        list1.add(b8);
        list1.add(b9);
        list1.add(b10);  
        list1.add(b11);
        list1.add(b12);
        list1.add(b13);
        list1.add(b14);
        list1.add(b15);
        list1.add(b16);
        list1.add(b17);
        list1.add(b18);
        list1.add(b19);
        list1.add(b20);
            
            jLabel3.setVisible(true);
            jLabel4.setVisible(true);
            jComboBox1.setEnabled(true);
            kontrol = 0;
            ipucu.setEnabled(true);
            coz.setEnabled(true);
            counter1 = 0;
            counter = 0;
            jLabel2.setText(0+" ");
            for (int i = 0; i < list1.size(); i++) {
                list1.get(i).setEnabled(true);
            }
            list3.clear();
            list2.clear();
            for (int i = 0; i < list1.size(); i++) {
                list1.get(i).setIcon(null);
            }
            list1.clear();
            
             int[] dizi = new int[20];
         
         ImageIcon karpuz,ananas,cilek,
                   domates,havuc,
                   kiraz,kivi,muz,
                   patlican,portakal;  
         
         karpuz = new ImageIcon("icon/karpuz.png");      
         ananas = new ImageIcon("icon/ananas.png");      
         cilek = new ImageIcon("icon/cilek.png");        
         domates = new ImageIcon("icon/domates.png");    
         havuc = new ImageIcon("icon/havuc.png");        
         kiraz = new ImageIcon("icon/kiraz.png");        
         kivi = new ImageIcon("icon/kivi.png");          
         muz = new ImageIcon("icon/muz.png");            
         patlican = new ImageIcon("icon/patlican.png");
         portakal = new ImageIcon("icon/portakal.png");  
         
        list1.add(b1);  
        list1.add(b2);
        list1.add(b3);
        list1.add(b4);
        list1.add(b5);
        list1.add(b6);
        list1.add(b7);
        list1.add(b8);
        list1.add(b9);
        list1.add(b10);  
        list1.add(b11);
        list1.add(b12);
        list1.add(b13);
        list1.add(b14);
        list1.add(b15);
        list1.add(b16);
        list1.add(b17);
        list1.add(b18);
        list1.add(b19);
        list1.add(b20);
         
         list2.add(karpuz);    
         list2.add(ananas);    
         list2.add(cilek);     
         list2.add(domates);   
         list2.add(havuc);    
         list2.add(kiraz);     
         list2.add(kivi);      
         list2.add(muz);       
         list2.add(patlican);  
         list2.add(portakal);  
         list2.add(karpuz);    
         list2.add(ananas);    
         list2.add(cilek);     
         list2.add(domates);   
         list2.add(havuc);    
         list2.add(kiraz);     
         list2.add(kivi);      
         list2.add(muz);       
         list2.add(patlican);  
         list2.add(portakal);  
        
         int a;         
         int sayac = 0;
        
        a = generator.nextInt(20)+1;
        dizi[0] = a;
        for (int k = 1; k < dizi.length;) {
            sayac = 0;
            a = generator.nextInt(20)+1;
            //System.out.println(a+" ");
            for (int j = 0; j < dizi.length; j++) {
                if (dizi[j] == a) {
                    sayac++;  break;                  
                }
            }
            if (sayac == 0) {
                dizi[k] = a; k++;  
                
            }
            else continue;
        }
        
        for (int k = 0; k < list2.size() ; k++) {
            list3.add(list2.get(dizi[k]-1));            
            //list1.get(k).setIcon(list2.get(dizi[k]-1));
        }
        }
        
        
        //ipucu butonu  . her oyunda bir kere tiklanabilir.  1.5 sn boyunca tum meyveler gorunur olur ve kapanir.
        if (b == ipucu) {
            if (kontrol == 0) {
                for (int i = 0; i < list1.size(); i++) {
                   
                 list1.get(i).setIcon(list3.get(i));
                }
             Timer t = new Timer(1500, new ActionListener() {         
                 @Override
                 public void actionPerformed(ActionEvent e) { 
                     for (int i = 0; i < list1.size(); i++) {
                         list1.get(i).setIcon(null); 
                     }
                   
                 }});  
                 kontrol++; ipucu.setEnabled(false);
                 t.setRepeats(false);        
                 t.start();
            }
        }
        
        
        if (b == coz) {
         tiklanmaKontrolu ++;
         jLabel3.setVisible(false);
         jLabel4.setVisible(false);
         jComboBox1.setEnabled(false);
         to++;
         ipucu.setEnabled(false);
         coz.setEnabled(false);
         
            Timer t = new Timer(250, new ActionListener() { 
                
           public void actionPerformed(ActionEvent e) {                      
                    
                    x = generator.nextInt(list1.size());
                    y = generator.nextInt(list1.size());
                if ((x != y) && (list1.get(x) != null) && (list1.get(y) != null) && (list3.get(x) != null) && (list3.get(y) != null) ) {                    
                    list1.get(x).setIcon(list3.get(x));
                    list1.get(y).setIcon(list3.get(y));
                   
                 if (list1.get(x).getIcon() == list1.get(y).getIcon()) { 
                    Timer t = new Timer(150, new ActionListener() { 
                         @Override
                         public void actionPerformed(ActionEvent e) { 
                        
                          list1.get(x).setIcon(null);
                          list1.get(x).setEnabled(false); 
                          list1.get(y).setIcon(null); 
                          list1.get(y).setEnabled(false); 
                          jLabel2.setText(counter+"");
                          list1.set(x, null);
                          list1.set(y, null);
                          list3.set(x, null);
                          list3.set(y, null);
                          
                         }}); 
                            t.setRepeats(false);                            
                            t.start();
                            counter++;
                            kapali1++;
                            if (kapali1 == 10) {
                                jLabel8.setVisible(true);
                                tekrarOyna.setEnabled(true);
                            }
                 }
                    
                 else if(list1.get(x).getIcon() != list1.get(y).getIcon()) {                     
                    Timer t = new Timer(150, new ActionListener() {         
                        @Override
                        public void actionPerformed(ActionEvent e) {                            
                          list1.get(x).setIcon(null);  
                          list1.get(y).setIcon(null);  
                          jLabel2.setText(counter+"");
                        }});  
                           t.setRepeats(false);        
                           t.start();
                           counter++;
                 } 
                } 
           }
         });
            t.setRepeats(true);
            t.start();
        }
        
       
        
    }//GEN-LAST:event_b

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
        if ( jComboBox1.getSelectedIndex() == 0) {
            time = 1000;
        }
        else if ( jComboBox1.getSelectedIndex() == 1) {
            time = 1500;
        }
        else if ( jComboBox1.getSelectedIndex() == 2) {
            time = 2000;
        }
        else if ( jComboBox1.getSelectedIndex() == 3) {
            time = 2500;
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HafizaOyunu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HafizaOyunu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HafizaOyunu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HafizaOyunu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HafizaOyunu().setVisible(true);
                
            }
        });
    }
  
            



 
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b10;
    private javax.swing.JButton b11;
    private javax.swing.JButton b12;
    private javax.swing.JButton b13;
    private javax.swing.JButton b14;
    private javax.swing.JButton b15;
    private javax.swing.JButton b16;
    private javax.swing.JButton b17;
    private javax.swing.JButton b18;
    private javax.swing.JButton b19;
    private javax.swing.JButton b2;
    private javax.swing.JButton b20;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JButton coz;
    private javax.swing.JButton ipucu;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton tekrarOyna;
    // End of variables declaration//GEN-END:variables
}


